### ISSUE TITLE
This repo is not really using renderscript support mode

### ISSUE THREAD

**Issue by rpattabi** [EE202B/RenderScriptOps#1]
I have tried to take this repo as an example of using renderscript support mode through NDK. After a while, I realized that this repo is setting `minSdkVersion` to 24. This means renderscript isn't needed to be run in support mode through Android.mk mentions `LOCAL_RENDERSCRIPT_COMPATIBILITY := true`.

I believe moving from cmake to ndk-build is mainly to make the support mode work. That was really not a success here.

Please correct me if I'm wrong. If so, how can I have `minSdkVersion` as 19 and still make use of reduction kernel, for example, which is part of 24 and only available through renderscript support library for older versions?

**Comment by coroner4817** [comment]
What is renderscript support mode? I don't understand your question here
If Renderscript is not running then who is doing the calculation and pass the test?

Check your phone, a lot of Android phone don't really support running renderscript on GPU. I guess this is what you are trying to ask. Try with a Google pixel phone instead

**Comment by rpattabi** [comment]
> what is renderscript support mode?

https://developer.android.com/guide/topics/renderscript/compute#ide-setup
